<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Table contact_request : persistance des demandes du formulaire de contact.
 */
final class Version20260715090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création de la table contact_request (demandes du formulaire de contact)';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Cette migration est prévue pour PostgreSQL.',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE contact_request (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                motif VARCHAR(20) NOT NULL,
                nom VARCHAR(120) NOT NULL,
                societe VARCHAR(120) DEFAULT NULL,
                email VARCHAR(180) NOT NULL,
                message TEXT NOT NULL,
                ip VARCHAR(45) DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_contact_request_created_at ON contact_request (created_at)');
        $this->addSql("COMMENT ON COLUMN contact_request.created_at IS '(DC2Type:datetimetz_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE contact_request');
    }
}
